### ISSUE TITLE
Display of content 

### ISSUE THREAD

**Issue by jsvt-AG** [Staatsarchiv-Aargau/koenigsfelden-app#20]
Content (Familien/Organisationen) is cut off when the screen is minimized. Can this be modified?

![image](https://github.com/Staatsarchiv-Aargau/koenigsfelden-app/assets/127207004/f243ff0f-eb19-4d0a-8bfc-590caa57f1fb)

**Comment by HelenaSabel** [comment]
Note for myself: This is not an issue if Firefox, but confirmed in Chrome.
![image](https://github.com/Staatsarchiv-Aargau/koenigsfelden-app/assets/8516387/5115d29d-b91a-42ca-a9f7-6d60b11e60bd)

**Comment by jsvt-AG** [comment]
@HelenaSabel 

I can confirm this issue also for Firefox and Edge

![image](https://github.com/Staatsarchiv-Aargau/koenigsfelden-app/assets/127207004/453dff8d-a053-4d3c-a4cf-7445c0a69bea)

as well as for the mobile version
![image](https://github.com/Staatsarchiv-Aargau/koenigsfelden-app/assets/127207004/42197f37-8212-4723-bacb-1ff717b2755b)

**Comment by HelenaSabel** [comment]
@jsvt-AG My [screenshot above](https://github.com/Staatsarchiv-Aargau/koenigsfelden-app/issues/20#issuecomment-2064935642) was from Firefox mobile, and in my version of Firefox Desktop it looks good as well (see below). But it doesn’t matter, the comment was a note for me to test it only in Chrome since all my instances of Firefox are displaying the content correctly


![image](https://github.com/Staatsarchiv-Aargau/koenigsfelden-app/assets/8516387/9ec4e7e8-bf63-4115-9f67-8af4d0ef775b)

**Comment by jsvt-AG** [comment]
Looks great now:
![image](https://github.com/Staatsarchiv-Aargau/koenigsfelden-app/assets/127207004/258c69a3-b98d-457f-bafa-d27b6ef37bbd)

not for myself: last check on safari open

**Comment by jsvt-AG** [comment]
perfect in safari as well

**Comment by jsvt-AG** [comment]
Dear @HelenaSabel weardly the problem returned. Could you check again?

**Comment by HelenaSabel** [comment]
Apologies: my mistake.

**Comment by jsvt-AG** [comment]
great! Thank you very much!
