### ISSUE TITLE
Dokumente: Not assigned Tick-Box

### ISSUE THREAD

**Issue by jsvt-AG** [Staatsarchiv-Aargau/koenigsfelden-app#23]
Could you delete the not assigned tick-box?

See: https://koenigsfelden.sources-online.org/data/docs/U-17_0434.xml
![image](https://github.com/Staatsarchiv-Aargau/koenigsfelden-app/assets/127207004/41facf65-a0ab-4f38-89f3-5633e2093ac6)

I found this one by chance. So the question for me is: is there a systematic and automated way to check, if there are more of these?

**Comment by HelenaSabel** [comment]
@jsvt-AG This is due to a reference ID in the text not being found in the register. I corrected it in [this commit](https://github.com/Staatsarchiv-Aargau/koenigsfelden-data/commit/645dbe185267fe4438ca0fd41e15d5ef11f8d7cc) but I haven’t deployed the new version yet. The `\u0009` is the encoding of a tabular character. I cleaned those from the register IDs when I prepared the data from the old app without realising that if that character was in the ID for the entities, it was likely also contained in the reference in the text. 

I can indeed test automatically that all the references of the text are in the register. I will report about this on our meeting on Monday.

**Comment by jsvt-AG** [comment]
@HelenaSabel I doublechecked with Tobias: see correct IDs above

**Comment by HelenaSabel** [comment]
@jsvt-AG I corrected the references (and one other that was not in the list, but it was very straightforward)

**Comment by jsvt-AG** [comment]
@HelenaSabel I tested the references. looks great, but three things are still open. see above

**Comment by HelenaSabel** [comment]
@jsvt-AG: I won’ t upload a new version to the server before the go-live, but I corrected the encoding issues here:  https://github.com/Staatsarchiv-Aargau/koenigsfelden-data/commit/1e3dc4b22820d53ab4f421341d8d964d486e8e3c

For the problem you noticed with the highlight is that most likely you gave me the wrong ID when correcting one of Heinrich’s mentions (could it be that you gave me the ID of Rudolf instead?): would you be ok with doing this correction yourself?

**Comment by jsvt-AG** [comment]
Dear @HelenaSabel - great! Thank you so much for solving the encoding problem! So I'll doublechek tomorrow, when the new version is uploaded. 

regarding StAAG U.17/0033 (Heinrich/Richard)
I updated the regarding parts here: https://github.com/Staatsarchiv-Aargau/koenigsfelden-data/blob/main/data/docs/U-17_0033.xml
