### ISSUE TITLE
Dokumente: Searchfunction

### ISSUE THREAD

**Issue by jsvt-AG** [Staatsarchiv-Aargau/koenigsfelden-app#25]
As a user I really like the new function, that search terms are suggested to me directly during the search. But not all search terms lead to search results.

For example: ag_ii_2
See:
![image](https://github.com/Staatsarchiv-Aargau/koenigsfelden-app/assets/127207004/766035c6-8b00-4025-b43e-cc7614e9e279)

How do these suggestions come about and could the indexing be checked if it was necessary?

**Comment by HelenaSabel** [comment]
@jsvt-AG Ready for testing.

The suggestions are created by the [full text index module](https://exist-db.org/exist/apps/doc/lucene), configured here: https://github.com/Staatsarchiv-Aargau/koenigsfelden-data/blob/main/collection.xconf

Reducing the complexity, we can say that the suggestions are the result of tokenizing the `<text>` element of the TEI documents. That particular suggestion came about because it was present in a URL (and Lucene interprets that if you have something like `string1/string2`, `string1` and `string2` are two different tokens. There URLs were part of the metadata in the registers, and those files shouldn’t have been indexed anyway, so that’s how I corrected the issue.

There is an API endpoint to retrieve the suggestions. For example, the first 30 suggestions for the query `so`  are available at https://koenigsfelden.sources-online.org/api/search/autocomplete?query=so&field=text and all and the suggestions for the query “gub” are available at https://koenigsfelden.sources-online.org/api/search/autocomplete?query=gub&field=text

If it was necessary, I guess I could provide a list with all the indexed tokens.

**Comment by jsvt-AG** [comment]
> There URLs were part of the metadata in the registers, and those files shouldn’t have been indexed anyway, so that’s how I corrected the issue.

Perfect! Thank you very much!

> Reducing the complexity, we can say that the suggestions are the result of tokenizing the <text> element of the TEI documents.

Could we talk about this on Monday? As far as I can see, everything looks fine now

**Comment by jsvt-AG** [comment]
thank you very much!
