### ISSUE TITLE
Dokumente: Toggle full page

### ISSUE THREAD

**Issue by jsvt-AG** [Staatsarchiv-Aargau/koenigsfelden-app#27]
Toggle full page in the view Digitalisat seems not to work for Safari. Full page view openes for a second but is then closed again. Could this be adapted?

**Comment by HelenaSabel** [comment]
@jsvt-AG Colleagues with Safari don’t report any issues. 

Without being able to reproduce the error, this is very hard to debug. At the very least, we should know the Safari version (to understand if the problem is that the user is using an out-of-date version), and then more information from the browser debugger tools should be provided.
