### ISSUE TITLE
Register - Personen: sorting

### ISSUE THREAD

**Issue by jsvt-AG** [Staatsarchiv-Aargau/koenigsfelden-app#7]
If all persons are displayed, something does not seem to be working correctly with the sorting.

Edge, Firefox, Chrome, Safari:
![image](https://github.com/Staatsarchiv-Aargau/koenigsfelden-app/assets/127207004/d61c9eda-02a8-414e-853e-87ee1ad55359)

**Comment by HelenaSabel** [comment]
@jsvt-AG
The first error (for Kaspar von Memmerswill) was due to erroneous whitespace in the register file: it’s a straightforward change.

The second problem is more complicated. The data for the entity affected is incomplete. In the old app, you can see the document where this person is cited here: https://www.koenigsfelden.uzh.ch/exist/apps/ssrq/docs/U-17_0563.xml

It concerns the entity that appears in the register list just with the year:

![image](https://github.com/Staatsarchiv-Aargau/koenigsfelden-app/assets/8516387/1db64d27-6563-4f0b-aa17-1ad6ec6424fd)

But this person is mentioned in the document as 
![image](https://github.com/Staatsarchiv-Aargau/koenigsfelden-app/assets/8516387/c451f22a-1b04-46ec-a467-01890b13364f)

This is the entry for that person in the old app only contains the name “Konrad” and the year of the first mention: https://www.koenigsfelden.uzh.ch/exist/apps/ssrq/detail.html?ref=per029111

Could you tell me how this person should be named? Even if we only use “Konrad”, it should be “Konrad NN” to follow the naming convention of the project, right? But considering the citation of the text, it might be appropriate to add “Stecheli” as last name...

**Comment by jsvt-AG** [comment]
Dear @HelenaSabel 
Regarding Tobias it should be: "Konrad Stechelin"

**Comment by jsvt-AG** [comment]
Great, only thing: Do you know why Konrad is listed here? Should I ask Tobias about it?
https://koenigsfelden.sources-online.org/detail.html?ref=org001791

![image](https://github.com/Staatsarchiv-Aargau/koenigsfelden-app/assets/127207004/0fec75a3-ae89-4a27-8e1f-897d946a2b26)

**Comment by HelenaSabel** [comment]
I took it from one of the JSON files of the old app. In the entry for the family in SSRQ you can see the different variants of the family name: https://www.ssrq-sds-fds.ch/persons-db-edit/?query=org001791

Please confirm it with Tobias and I will take it out if it isn’t pertinent.

**Comment by jsvt-AG** [comment]
Tobias' Feedback: «Familie» sollten im SSRQ (und entsprechend auch Königsfelden) Kontext immer in Anführungszeichen gesetzt werden. Da es «nur» um die Kombination des gleichen Nachnamens geht. Wobei es in wenigen Fällen auch explizite Familien gibt, die sind jedoch entsprechend markiert.
Entsprechend ist das bei dem Fall kein Problem.

“Family” should always be placed in quotation marks in the SSRQ (and correspondingly Königsfelden) context. As it is “only” about the combination of the same surname. In a few cases there are also explicit families, but these are marked accordingly.
Accordingly, this is not a problem in this case.

**Comment by jsvt-AG** [comment]
see comment above
